/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      D:/ti/grace_3_10_00_82/packages/ti/mcu/msp430/csl2/adc/ADC12_B_init.xdt
 */
#include <driverlib/MSP430FR5xx_6xx/inc/hw_memmap.h>
#include <driverlib/MSP430FR5xx_6xx/adc12_b.h>
#include "_Grace.h"

/* USER CODE START (section: ADC12_B_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: ADC12_B_init_c_prologue) */

/*
 *  ======== ADC12_B_graceInit ========
 *  Initialize Config for the MSP430 12-bit Analog to Digital Converter (ADC12)
 */
void ADC12_B_graceInit(void)
{
    /* Struct to pass to ADC12_B_init */
    ADC12_B_initParam initParam = {0};

    /* Struct to pass to ADC12_B_configureMemory */
    ADC12_B_configureMemoryParam configureMemoryParam = {0};

    /* USER CODE START (section: ADC12_B_graceInit_prologue) */
    /* User initialization code */
    /* USER CODE END (section: ADC12_B_graceInit_prologue) */

    /* Initializes ADC12_B */
    initParam.sampleHoldSignalSourceSelect = ADC12_B_SAMPLEHOLDSOURCE_SC;
    initParam.clockSourceSelect = ADC12_B_CLOCKSOURCE_ADC12OSC;
    initParam.clockSourceDivider = ADC12_B_CLOCKDIVIDER_1;
    initParam.clockSourcePredivider = ADC12_B_CLOCKPREDIVIDER__1;
    initParam.internalChannelMap = 0;
    ADC12_B_init(ADC12_B_BASE, &initParam);

    /* Enables ADC12_B */
    ADC12_B_enable(ADC12_B_BASE);

    /* Sets up and enables the Sampling Timer Pulse Mode */
    ADC12_B_setupSamplingTimer(ADC12_B_BASE, ADC12_B_CYCLEHOLD_8_CYCLES, ADC12_B_CYCLEHOLD_8_CYCLES, ADC12_B_MULTIPLESAMPLESENABLE);

    /* Configures the memory buffer 1 */
    configureMemoryParam.memoryBufferControlIndex = ADC12_B_MEMORY_1;
    configureMemoryParam.inputSourceSelect = ADC12_B_INPUT_A1;
    configureMemoryParam.refVoltageSourceSelect = ADC12_B_VREFPOS_AVCC_VREFNEG_VSS;
    configureMemoryParam.endOfSequence = ADC12_B_ENDOFSEQUENCE;
    configureMemoryParam.windowComparatorSelect = ADC12_B_WINDOW_COMPARATOR_DISABLE;
    configureMemoryParam.differentialModeSelect = ADC12_B_DIFFERENTIAL_MODE_DISABLE;
    ADC12_B_configureMemory(ADC12_B_BASE, &configureMemoryParam);

    /* Inverts/Uninverts the sample/hold signal */
    ADC12_B_setSampleHoldSignalInversion(ADC12_B_BASE, ADC12_B_NONINVERTEDSIGNAL);

    /* Sets the read-back format of the converted data */
    ADC12_B_setDataReadBackFormat(ADC12_B_BASE, ADC12_B_UNSIGNED_BINARY);

    /* Enables interrupt */
    ADC12_B_enableInterrupt(ADC12_B_BASE, 0, 0, 0);

    /* Disables interrupt */
    ADC12_B_disableInterrupt(ADC12_B_BASE, ADC12_B_IE0+ADC12_B_IE1+ADC12_B_IE2+ADC12_B_IE3+ADC12_B_IE4+ADC12_B_IE5+ADC12_B_IE6+ADC12_B_IE7+ADC12_B_IE8+ADC12_B_IE9+ADC12_B_IE10+ADC12_B_IE11+ADC12_B_IE12+ADC12_B_IE13+ADC12_B_IE14+ADC12_B_IE15, ADC12_B_IE16+ADC12_B_IE17+ADC12_B_IE18+ADC12_B_IE19+ADC12_B_IE20+ADC12_B_IE21+ADC12_B_IE22+ADC12_B_IE23+ADC12_B_IE24+ADC12_B_IE25+ADC12_B_IE26+ADC12_B_IE27+ADC12_B_IE28+ADC12_B_IE29+ADC12_B_IE30+ADC12_B_IE31, ADC12_B_HIIE+ADC12_B_LOIE+ADC12_B_INIE);

    /* USER CODE START (section: ADC12_B_graceInit_epilogue) */
    /* User code */
    /* USER CODE END (section: ADC12_B_graceInit_epilogue) */

}
