/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      D:/ti/grace_3_10_00_82/packages/ti/mcu/msp430/csl2/pinmux/PinMux_init.xdt
 */
#include <driverlib/MSP430FR5xx_6xx/inc/hw_memmap.h>
#include <driverlib/MSP430FR5xx_6xx/pmm.h>
#include "_Grace.h"

/* USER CODE START (section: PinMux_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: PinMux_init_c_prologue) */

/*
 *  ======== PinMux_graceInit ========
 *  Initialize 
 *
 *  The PinMux registers should be set in a specific order:
 *     PxOUT
 *     PxSEL or PxSELx
 *     PxDIR
 *     PxREN
 *     PxIES
 *     PxIFG
 *     PxIE
 *
 *     This will ensure that:
 *         - IFG doesn't get set by manipulating the pin function, edge
 *           select, and pull-up/down resistor functionalities (see
 *           Section 8.2.6 of the MSP430 User's manual)
 *         - Glitch-free setup (configuring the OUT register _before_
 *           setting the pin direction)
 *         - Pull-up/pull-down resistor enable with the correct direction
 *           (.up. vs. .down.)
 */
void PinMux_graceInit(void)
{

    /* USER CODE START (section: PinMux_graceInit_prologue) */
    /* User initialization code */
    /* USER CODE END (section: PinMux_graceInit_prologue) */

    /* Port 1 Output Register */
    P1OUT = 0;

    /* Port 1 Port Select Register 0 */
    P1SEL0 = BIT0 | BIT1;

    /* Port 1 Port Select Register 1 */
    P1SEL1 = BIT0 | BIT1 | BIT3 | BIT5 | BIT6 | BIT7;

    /* Port 1 Direction Register */
    P1DIR = BIT4;

    /* Port 1 Interrupt Edge Select */
    P1IES = 0;

    /* Port 1 Interrupt Flag Register */
    P1IFG = 0;

    /* Port 2 Output Register */
    P2OUT = BIT7;

    /* Port 2 Port Select Register 1 */
    P2SEL1 = BIT0 | BIT1 | BIT2 | BIT4 | BIT5 | BIT6;

    /* Port 2 Direction Register */
    P2DIR = 0;

    /* Port 2 Resistor Enable Register */
    P2REN = BIT1 | BIT7;

    /* Port 2 Interrupt Edge Select */
    P2IES = 0;

    /* Port 2 Interrupt Flag Register */
    P2IFG = 0;

    /* Port J Output Register */
    PJOUT = BIT0 | BIT1 | BIT2 | BIT3;

    /* Port J Port Select Register 0 */
    PJSEL0 = BIT4 | BIT5;

    /* Port J Direction Register */
    PJDIR = BIT0 | BIT1 | BIT2 | BIT3;

    /* USER CODE START (section: PinMux_graceInit_epilogue) */
    /* User code */
    /* USER CODE END (section: PinMux_graceInit_epilogue) */
}
